---
# tasks file for enrollment_ansible

- name: Clean the subscription-manager config
  shell: subscription-manager clean

- name: Disable subscription-manager plugin for yum
  lineinfile:
    path: /etc/yum/pluginconf.d/subscription-manager.conf
    regexp: '^enabled='
    line: 'enabled=0'

- name: Remove previous registration data
  file:
    path: /etc/pki/consumed/cert.pem
    state: absent

- name: Remove Satellite 5 registration locally
  file:
    path: /etc/sysconfig/rhn/systemid
    state: absent

- name: Find and register all the files in /etc/yum.repos.d/
  find:
    paths: /etc/yum.repos.d/
    patterns: '*.repo,*.rpmnew'
  register: repos_conf

- name: Backup the files in /etc/yum.repos.d/
  command: "mv {{ item.path }} {{ item.path }}.bak.{{ timestamp }}"
  with_items: "{{ repos_conf.files }}"

- name: Ensure remote execution user {{ rex_user }} exists
  user:
    name: "{{ rex_user }}"
    home: "{{ home_dir }}"
    expires: -1

- name: Ensure {{ rex_user }} user is in the sudoers
  lineinfile:
    create: yes
    path: "{{ sudoers }}"
    state: present
    line: "{{ rex_user }} ALL = (root) NOPASSWD: ALL"

- name: Download bootstrap.py from {{ foreman_fqdn }}
  get_url:
    dest: "{{ bootstrap_path }}"
    url: "{{ download_method }}://{{ foreman_fqdn }}/pub/bootstrap.py"

- name: Operating system definition for RHEL hosts
  set_fact:
    ansible_distribution: "RHEL Server"
  when: ansible_distribution == "RedHat"

- name: Generate bootstrap.py arguments
  set_fact:
    bootstrap_args: "--server '{{ foreman_fqdn }}' --organization '{{ organization }}' --location '{{ location }}' --download-method '{{ download_method }}' --fqdn '{{ ansible_hostname }}' --enablerepos '{{ repos }}'"
    bootstrap_foreman_args: "{% if password != '' %}--login '{{ login }}' --password '{{ password }}' --hostgroup '{{ hostgroup }}'{% else %}--skip foreman{% endif %} --activationkey '{{ activationkey }}'"
    bootstrap_additional_args: "--skip katello-agent --skip puppet --force --rex --rex-user '{{ rex_user }}' --operatingsystem '{{ ansible_distribution }} {{ ansible_distribution_version }}'"

- name: Run bootstrap.py
  shell: "python {{ bootstrap_path }} {{ bootstrap_args }} {{ bootstrap_foreman_args }} {{ bootstrap_additional_args }}"

- name: Remove bootstrap.py
  file:
    path: "{{ bootstrap_path }}"
    state: absent
